/// Files: drivers/misc/fastrpc.c
/// Fix: 20c40794eb85ea29852d7bc37c55713802a543d6
/// Fixes: c68cfb718c8f97b7f7a50ed66be5feb42d0c8988

virtual detect

@err exists@
identifier fl, kernel, handle;
position p;
@@

fastrpc_internal_invoke(struct fastrpc_user *fl,  u32 kernel,
			u32 handle, ...)
{
	... when != if (handle == FASTRPC_INIT_HANDLE && !kernel) { ... return -EPERM; }
*	fastrpc_invoke_send@p(fl->sctx, ..., kernel, handle)
	...
}

@script:python depends on detect@
p << err.p;
@@

coccilib.report.print_report(p[0], 'ERROR: CVE-2021-28375')
