/// Files: arch/x86/kvm/hyperv.c arch/x86/include/asm/kvm_host.h
/// Fix: 919f4ebc598701670e80e31573a58f1f2d2bf918
/// Fixes: 8f014550dfb114cc7f42a517d20d2cf887a0b771

virtual detect

@hyperv_enabled@
@@

struct kvm_vcpu_arch {
	...
*	bool hyperv_enabled;
	...
};

@err depends on hyperv_enabled exists@
identifier vcpu;
position p;
@@

synic_get(...)
{
	...
* 	vcpu =@p get_vcpu_by_vpidx(...);
	... when != to_hv_vcpu(vcpu)
*	to_hv_synic(vcpu)
	...
}

@script:python depends on detect@
p << err.p;
@@

coccilib.report.print_report(p[0], 'ERROR: CVE-2021-30178')
