/// Files: drivers/usb/dwc3/dwc3-pci.c
/// Fix: 9bbfceea12a8f145097a27d7c7267af25893c060
/// Fixes: 1a7b12f69a9434a766e77c43d113826f0413b032
/// Version: 1.1.0

virtual detect

@err exists@
identifier dwc, ret, err;
position p;
@@

dwc3_pci_probe(...)
{
	...
*	dwc->dwc3 = platform_device_alloc(...);
	...
*	ret = platform_device_add_properties(dwc->dwc3, ...);
	... when != ret;
* 	if (ret < 0)
*		return ret;@p
	...
err:
*	platform_device_put(dwc->dwc3);
	...
}

@script:python depends on detect@
p << err.p;
@@

coccilib.report.print_report(p[0], 'ERROR: CVE-2019-18813')
