/// Files: fs/io_uring.c
/// Fix: d1f82808877bb10d3deee7cf3374a4eb3fb582db
/// Fixes: ddf0322db79c5984dc1a1db890f946dd19b7d6d9

virtual detect

@err exists@
identifier buf, pbuf;
position p;
@@

io_add_buffers(struct io_provide_buf *pbuf, ...)
{
	...
*	buf->len =@p pbuf->len;
	...
}


@script:python depends on detect@
p << err.p;
@@

coccilib.report.print_report(p[0], 'ERROR: CVE-2021-3491')
