/// Files: net/nfc/llcp_sock.c net/nfc/llcp/sock.c
/// Fix: 8a4cd82d62b5ec7e5482333a72b58a4eea4979f0
/// Fixes: c7aa12252f5142b9eee2f6e34ca8870a8e7e048c

virtual detect

@err1 exists@
identifier llcp_sock, put;
position p;
@@

llcp_sock_connect(...)
{
	...
*	llcp_sock->local = nfc_llcp_local_get(...);
	...
	if (llcp_sock->ssap == LLCP_SAP_MAX) {
		... when != nfc_llcp_local_put(llcp_sock->local);
*		goto put;@p
	}
	...
put:
	... when != nfc_llcp_local_put(llcp_sock->local);
}

@err2 exists@
identifier llcp_sock;
position p;
@@

llcp_sock_connect(...)
{
	...
*	llcp_sock->local =@p nfc_llcp_local_get(...);
	...
	nfc_llcp_put_ssap(..., llcp_sock->ssap);
	... when != nfc_llcp_local_put(llcp_sock->local);
}

@script:python depends on detect@
p << err1.p;
@@

coccilib.report.print_report(p[0], 'ERROR: CVE-2020-25671')

@script:python depends on detect@
p << err2.p;
@@

coccilib.report.print_report(p[0], 'ERROR: CVE-2020-25671')
