/// Files: drivers/net/can/usb/peak_usb/pcan_usb_core.c
/// Fix: f7a1337f0d29b98733c8824e165fca3371d7d4fd
/// Fixes: bb4785551f64e18b2c8bb15a3bd2b22f5ebf624d

virtual detect

@err exists@
identifier dev;
position p;
@@

peak_usb_create_dev(...)
{
	...
*	dev->cmd_buf =@p kmalloc(PCAN_USB_MAX_CMD_LEN, GFP_KERNEL);
	...
}

@script:python depends on detect@
p << err.p;
@@

coccilib.report.print_report(p[0], 'ERROR: CVE-2019-19534')
